packages:
  - apps/*
  - packages/*

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@clerk/shared'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - browser-tabs-lock
  - core-js
  - esbuild
  - lefthook
  - sharp
  - unrs-resolver
  - workerd
